export const FILTER_CONTEXT_ACTION_TYPES = {
  COMMODITIES_AND_VARIETIES: 'COMMODITIES_AND_VARIETIES',
  COMMODITIES: 'COMMODITIES',
  SIZE: 'SIZE',
  PACKAGING: 'PACKAGING',
  DATE_RANGE: 'DATE_RANGE',
  CUSTOMER: 'CUSTOMER',
  IN_COMMODITY_SCOPE: 'IN_COMMODITY_SCOPE',
  IN_CUSTOMER_SCOPE: 'IN_CUSTOMER_SCOPE',
  RESTORE_FILTERS: 'RESTORE_FILTERS',
};
