export const FILTER_CONTEXT_ACTION_TYPES = {
  COMMODITIES_AND_VARIETIES: 'COMMODITIES_AND_VARIETIES',
  SIZE: 'SIZE',
  PACKAGING: 'PACKAGING',
  DATE_RANGE: 'DATE_RANGE',
  CUSTOMER: 'CUSTOMER',
  RESTORE_FILTERS: 'RESTORE_FILTERS',
};
