export const FILTER_CONTEXT_ACTION_TYPES = {
  COMMODITIES_AND_VARIETIES: 'COMMODITIES_AND_VARIETIES',
  SIZE: 'SIZE',
  PACKAGING: 'PACKAGING',
  DATE_RANGE: 'DATE_RANGE',
  CUSTOMER: 'CUSTOMER',
  SALES_PERSON: 'SALES_PERSON',
  COUNTRY_OF_ORIGIN: 'COUNTRY_OF_ORIGIN',
  LABEL: 'LABEL',
};
